# -*- coding: utf-8 -*-
"""Copy of Studio 3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1j3cxnovOBBzf_wv33fpxePdLQIUbPEWn
"""

from sklearn.metrics import mean_squared_error, mean_absolute_error
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
!pip install xgboost  # only run if xgboost isn't installed
from xgboost import XGBRegressor
from sklearn.metrics import r2_score, mean_squared_error, mean_absolute_error
from sklearn.ensemble import RandomForestRegressor
!pip install tensorflow
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import SimpleRNN, Dense

from google.colab import drive
drive.mount('/content/drive/')
import sys
print(sys.path)
sys.path.insert(0,'/content/drive/My Drive')
import pandas as pd
try:
 df = pd.read_csv('/content/drive/My Drive/BTCUSDT.csv')
 print("dataset loaded successfully")
except Exception:
 print("error loading dataset")

print(df.info()) #This function is used to get basic overview of data

print(df.describe())

print(df.tail())

df.drop(['number_of_trades'],axis=1,inplace=True) #removing unwanted columns
print(df.info())

print(df.head())

# Convert to datetime (if not already) and set as index
df['timestamp'] = pd.to_datetime(df['timestamp'])
df.set_index('timestamp', inplace=True)

df.head()

df.sort_index(inplace=True)
# Identify duplicates
duplicates = df.index.duplicated(keep=False)
print("Number of duplicate timestamps:", duplicates.sum())

print(df.isna().sum())

# Look at the differences between consecutive timestamps
freq_check = df.index.to_series().diff().value_counts()
print(freq_check)

# Resample to daily frequency
df_daily = df.resample('D').agg({
    'open': 'first',
    'high': 'max',
    'low': 'min',
    'close': 'last',
    'volume': 'sum',

})

# Drop any days that didn't have data (if needed)
df_daily.dropna(inplace=True)



# Check the result
print(df_daily.head())
print(df_daily.index)  # should now be daily

df_daily['close_lag1'] = df_daily['close'].shift(1)
df_daily['close_ma7']  = df_daily['close'].rolling(7).mean()
df_daily['daily_return'] = (df_daily['close'] - df_daily['close'].shift(1)) / df_daily['close'].shift(1)
df_daily.dropna(inplace=True)

# Example: Creating a target column (next-day close)
df_daily['target'] = df_daily['close'].shift(-1)
df_daily.dropna(subset=['target'], inplace=True)

# Suppose you have already added any extra features you want.
# For simplicity, we’ll use these columns as features:
feature_cols = ['open', 'high', 'low', 'close', 'volume']  # plus any additional engineered features

X = df_daily[feature_cols]
y = df_daily['target']

total_samples = len(df_daily)
train_size = int(total_samples * 0.7)
val_size = int(total_samples * 0.15)

X_train = X.iloc[:train_size]
y_train = y.iloc[:train_size]

X_val = X.iloc[train_size:train_size+val_size]
y_val = y.iloc[train_size:train_size+val_size]

X_test = X.iloc[train_size+val_size:]
y_test = y.iloc[train_size+val_size:]

xgb_model = XGBRegressor(
    n_estimators=100,
    max_depth=5,
    learning_rate=0.1,
    objective='reg:squarederror',
    random_state=42
)

xgb_model.fit(X_train, y_train)

y_pred_xgb = xgb_model.predict(X_test)

mse_xgb = mean_squared_error(y_test, y_pred_xgb)
rmse_xgb = np.sqrt(mse_xgb)
mae_xgb = mean_absolute_error(y_test, y_pred_xgb)
r2_xgb = r2_score(y_test, y_pred_xgb)

print("XGBoost Performance:")
print("MSE:", mse_xgb)
print("RMSE:", rmse_xgb)
print("MAE:", mae_xgb)
print("R²:", r2_xgb)

plt.figure(figsize=(10,5))
plt.plot(y_test.values[:100], label='True', marker='o')
plt.plot(y_pred_xgb[:100], label='XGBoost Predicted', marker='x')
plt.title("XGBoost Predictions vs True Values")
plt.xlabel("Sample Index")
plt.ylabel("Bitcoin Price")
plt.legend()
plt.show()

rf_model = RandomForestRegressor(
    n_estimators=100,    # You can try more trees for potentially better performance
    max_depth=5,         # Limit tree depth to help prevent overfitting
    random_state=42
)

rf_model.fit(X_train, y_train)

y_pred_rf = rf_model.predict(X_test)

mse_rf = mean_squared_error(y_test, y_pred_rf)
rmse_rf = np.sqrt(mse_rf)
mae_rf = mean_absolute_error(y_test, y_pred_rf)
r2_rf = r2_score(y_test, y_pred_rf)

print("Random Forest Performance:")
print("MSE:", mse_rf)
print("RMSE:", rmse_rf)
print("MAE:", mae_rf)
print("R²:", r2_rf)

import matplotlib.pyplot as plt

plt.figure(figsize=(10,5))
plt.plot(y_test.values[:100], label='True', marker='o')
plt.plot(y_pred_rf[:100], label='Predicted', marker='x')
plt.title("Random Forest Predictions vs True Values")
plt.xlabel("Sample Index")
plt.ylabel("Bitcoin Price")
plt.legend()
plt.show()

# Select features (you can expand this)
features = ['open', 'high', 'low', 'close', 'volume']
data = df_daily[features + ['target']].values

# Create sequences
def create_sequences(data, window_size):
    X, y = [], []
    for i in range(len(data) - window_size):
        X.append(data[i:i+window_size, :-1])  # input window
        y.append(data[i+window_size, -1])     # target (next day close)
    return np.array(X), np.array(y)

window_size = 7
X_rnn, y_rnn = create_sequences(data, window_size)

print("RNN input shape:", X_rnn.shape)  # (samples, time steps, features)

train_size = int(len(X_rnn) * 0.7)
val_size = int(len(X_rnn) * 0.15)

X_train_rnn = X_rnn[:train_size]
y_train_rnn = y_rnn[:train_size]

X_val_rnn = X_rnn[train_size:train_size + val_size]
y_val_rnn = y_rnn[train_size:train_size + val_size]

X_test_rnn = X_rnn[train_size + val_size:]
y_test_rnn = y_rnn[train_size + val_size:]

model_rnn = Sequential()
model_rnn.add(SimpleRNN(64, activation='tanh', input_shape=(window_size, len(features))))
model_rnn.add(Dense(1))  # output layer

model_rnn.compile(optimizer='adam', loss='mse')

history = model_rnn.fit(
    X_train_rnn, y_train_rnn,
    epochs=20,
    batch_size=32,
    validation_data=(X_val_rnn, y_val_rnn),
    verbose=1
)

y_pred_rnn = model_rnn.predict(X_test_rnn)

mse_rnn = mean_squared_error(y_test_rnn, y_pred_rnn)
rmse_rnn = np.sqrt(mse_rnn)
mae_rnn = mean_absolute_error(y_test_rnn, y_pred_rnn)
r2_rnn = r2_score(y_test_rnn, y_pred_rnn)

print("RNN Performance:")
print("MSE:", mse_rnn)
print("RMSE:", rmse_rnn)
print("MAE:", mae_rnn)
print("R²:", r2_rnn)

plt.figure(figsize=(10,5))
plt.plot(y_test_rnn[:100], label='True', marker='o')
plt.plot(y_pred_rnn[:100], label='RNN Predicted', marker='x')
plt.title("RNN Predictions vs True Values")
plt.xlabel("Sample Index")
plt.ylabel("Bitcoin Price")
plt.legend()
plt.show()